# Generated by Django 3.1 on 2020-09-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Site',
        ),
    ]
