# Generated by Django 3.1 on 2020-09-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200905_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='image',
        ),
    ]
