# Generated by Django 3.1 on 2020-09-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_site_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='image',
            field=models.ImageField(default='', upload_to='mediaFiles/images'),
        ),
    ]
